#!/usr/bin/env python3
"""Usage: update-index.py [dr-directory]

Decision Record のファイル群から <dr-dir>/README.md を再生成する。
stdout: 更新した index ファイルのパス
stderr: ディレクトリ不在などの失敗内容。exit 1
"""

import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

from dr_common import fail, guard_skill_dir, resolve_dr_dir, split_frontmatter

STATUS_SECTIONS = (
    ("proposed", "Proposed"),
    ("accepted", "Accepted"),
    ("deprecated", "Deprecated"),
    ("superseded", "Superseded"),
    ("rejected", "Rejected"),
)

HEADER = """\
# Decision Records

This directory contains important decisions about the project.

## DR List

| Number | Title | Status | Date |
|--------|-------|--------|------|
"""

FOOTER = """\
## About MADR Format

This project uses [MADR (Markdown Any Decision Records)](https://adr.github.io/madr/) format, v4.

### How to Create a Decision Record

```bash
/dr "Decision Title"
```

### Status Meanings

- **Proposed**: Awaiting review
- **Accepted**: Approved, implementing or completed
- **Rejected**: Considered but not adopted
- **Deprecated**: Retired without a replacement DR
- **Superseded**: Replaced by another DR (e.g. `superseded by DR-NNNN`)

---

*Last updated: {update_date}*
*Auto-generated by: update-index.py*
"""


def parse_dr(path: Path) -> tuple[str, str, str]:
    """(title, status, date) from frontmatter and the first # heading."""
    frontmatter, body = split_frontmatter(path.read_text(encoding="utf-8"))
    status = next(
        (
            line.removeprefix("status:").strip().strip('"')
            for line in frontmatter
            if line.startswith("status:")
        ),
        "",
    )
    date_str = next(
        (
            line.removeprefix("date:").strip().strip('"')
            for line in frontmatter
            if line.startswith("date:")
        ),
        "",
    )
    title = next((line[2:] for line in body if line.startswith("# ")), "")
    return title, status or "proposed", date_str or "Not set"


def main() -> None:
    dr_dir = resolve_dr_dir(sys.argv[1] if len(sys.argv) > 1 else None)
    if not dr_dir.is_dir():
        fail(f"Error: directory not found: {dr_dir}")
    guard_skill_dir(dr_dir, "Set DR_DIR env var or pass an explicit DR archive path.")

    rows: list[str] = []
    by_status: dict[str, list[tuple[str, str]]] = {key: [] for key, _ in STATUS_SECTIONS}
    for dr_file in sorted(dr_dir.rglob("[0-9][0-9][0-9][0-9]-*.md")):
        number = dr_file.name[:4]
        title, status, date_str = parse_dr(dr_file)
        rows.append(f"| [{number}]({dr_file.name}) | {title} | {status} | {date_str} |")
        for key, _ in STATUS_SECTIONS:
            if status.startswith(key):
                by_status[key].append((number, title))
                break

    parts = [HEADER + "\n".join(rows), "\n## By Status\n"]
    for key, heading in STATUS_SECTIONS:
        if by_status[key]:
            entries = "\n".join(f"- **{num}**: {title}" for num, title in sorted(by_status[key]))
            parts.append(f"### {heading}\n\n{entries}\n")
    parts.append(FOOTER.format(update_date=datetime.now().astimezone().date().isoformat()))

    index_file = dr_dir / "README.md"
    fd, temp_path = tempfile.mkstemp(dir=dr_dir)
    with os.fdopen(fd, "w", encoding="utf-8") as temp_file:
        _ = temp_file.write("\n".join(parts))
    _ = Path(temp_path).replace(index_file)

    print(index_file)


if __name__ == "__main__":
    main()
